accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    # path('<str:username>/follow/', views.FollowView.as_view(), name='follow'),
    # path('<str:username>/unfollow/', views.UnFollowView, name='unfollow'),
    # path('<str:username>/following_list/', views.FollowingListView.as_view(), name='following_list'),
    # path('<str:username>/follower_list/', views.FollowerListView.as_view(), name='follower_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    # path('create/', views.TweetCreateView.as_view(), name='create'),
    # path('<int:pk>/', views.TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/delete/', views.TweetDeleteView.as_view(), name='delete'),
    # path('<int:pk>/like/', views.LikeView, name='like'),
    # path('<int:pk>/unlike/', views.UnlikeView, name='unlike'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.WelcomeView.as_view()),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()


#   class FriendShip(models.Model):

tweets/models.py
# from django.db import models

# class Tweet(models.Model):
#     pass

welcome/models.py
# from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

accounts/views.py
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from .forms import SignUpForm

User = get_user_model()


class SignUpView(generic.CreateView):
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    model = User
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = get_object_or_404(User, username=self.kwargs["username"])
        ctx["username"] = user.username
        return ctx

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "tweets/home.html"

welcome/views.py
from django.views.generic import TemplateView


class WelcomeView(TemplateView):
    template_name = "welcome/index.html"

templates/accounts/login.html
{% extends "common/base.html" %}
{% block title %}ログイン{% endblock %}
{% block content %}
    <form method="post">
        {{ form }}
        {% csrf_token %}
        <button type="submit">ログイン</button>
    </form>
    <section>
        <p>
            または<a href="{% url 'accounts:signup' %}">サインアップ</a>
        </p>
    </section>
{% endblock %}

templates/accounts/profile.html
{% extends "common/base.html" %}
{% block title %}プロフィール{% endblock %}
{% block content %}
    <h1>{{ username }}</h1>
{% endblock %}

templates/accounts/signup.html
<form method = "POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type = "submit">ユーザー登録</button>
	</form>

templates/common/base.html
<body>
    <div class="page-header">
        <h1><a href="/">Twitter copy site</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>

templates/tweets/home.html
{% extends "common/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>
{% endblock %}

welcome/templates/welcome/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>WELCOME</title>
</head>
<body>
  <h1>Backend Final Assignment</h1>
</body>
</html>